### ISSUE TITLE
can't install on SS 4.0.1

### ISSUE THREAD

**Issue by hprata** [bigfork/silverstripe-oauth-login#11]
- Installation request for bigfork/silverstripe-oauth-login * -> satisfiable by bigfork/silverstripe-oauth-login[0.1.0, 0.2.0, 0.2.1, 0.2.2, 0.2.x-dev, 0.3.0, 1.0.0, dev-master].
    - Conclusion: don't install silverstripe/framework 4.0.1

Running SS 4.0.1 on PHP 7.0.22

**Comment by kinglozzer** [comment]
2.0.x-dev is now SS4 compatible and functional. Needs a bit more testing before a stable tag though
