### ISSUE TITLE
Extensions are not instantiated before updateActions or updateFields being called

### ISSUE THREAD

**Issue by BLMaciej** [bigfork/silverstripe-oauth-login#14]
I tried to add an my own extension to LoginForm via yml file to hook into updateActions, but I could get it to work. After some research it looks like that getActions is being called before the LoginForm constructor therefore silverstripe have no chance to initialize or instantiate the extensions before updateActions call happens.

The only fix that comes to my mind is to call the parent constructor with empty FieldList and set the one from LoginForm afterwards.

I am using silverstripe framework 3.6.4 and silverstripe oauth login 1.0.2

**Comment by kinglozzer** [comment]
I’ve just tagged `1.0.3` which includes the fix for this, thanks!

**Comment by BLMaciej** [comment]
thank you
