### ISSUE TITLE
Ugly login page / missing CSS

### ISSUE THREAD

**Issue by Sil3ntStorm** [bigfork/silverstripe-oauth-login#17]
The regular SS email login and the social sign on, are listed in an `<ul>` on the login form and drawn as separate boxes below each other, rather than being tabbed as they appear to have been intended to (given they have `form-tab` class). The CSS for that seems to be missing and, given that they have an unrelated unordered list above to link to them, I don't seem to be able to fix it with pure CSS.

If you intended that to be actual tabs then it should probably be something along the lines of [this](https://codepen.io/oknoblich/pen/tfjFl).

Where is all of the HTML even generated and how can we modify the Login Page to be proper and display nicely?

**Comment by kinglozzer** [comment]
This module intentionally doesn’t provide any styling, much in the same way that SilverStripe doesn’t provide any styling for login forms (unless you install a theme that offers it).

The “tabs” logic is something that the framework provides when you have multiple authentication methods. Again, the framework doesn’t provide any front-end styling/scripts there I’m afraid - you’ll need to implement that yourself.

**Comment by elliot-sawyer** [comment]
@Sil3ntStorm you need to overload `SilverStripe/Security/Security_MultiAuthenticatorTabbedForms.ss`. [I created a module ]( https://github.com/elliot-sawyer/watea-multiauthenticator-login/blob/master/templates/SilverStripe/Security/Security_MultiAuthenticatorTabbedForms.ss)to add tab support for a Bootstrap 3 project if you want an example to work from.
