### ISSUE TITLE
I18N

### ISSUE THREAD

**Issue by wernerkrauss** [bigfork/silverstripe-oauth-login#2]
We need to translate the UI stuff (e.g. login button)

**Comment by kinglozzer** [comment]
Ah, I thought I’d done something for this but I couldn’t remember what! You can override the template for each provider’s action button, e.g. https://github.com/bigfork/silverstripe-oauth-login#customisation.

The main form template should be easy to override too (`OAuthLoginForm.ss`), I’ve also used `_t()` calls in places ([like this](https://github.com/bigfork/silverstripe-oauth-login/blob/master/src/Authenticator/Authenticator.php#L34), though it might be a good idea to use a shorter entity name 😉).

Let me know if you spot anywhere else that needs to be updated!

**Comment by kinglozzer** [comment]
Re-opening as a reminder to translate error messages as part of the work for https://github.com/bigfork/silverstripe-oauth/issues/1

**Comment by kinglozzer** [comment]
Thinking about it again, I don’t think it makes sense to translate those errors. They’re only shown if there isn’t a suitable `ErrorPage` set up for that response code, so the translations can be done in there
