### ISSUE TITLE
Facebook login - Invalid access token. 

### ISSUE THREAD

**Issue by jsirish** [bigfork/silverstripe-oauth-login#22]
Is there a trick to get this to work with Facebook? I'm able to trigger the Facebook login form, and Facebook creates a notification that I've logged into the Facebook app. However, when it directs back to my website I always get `Invalid access token.`

I've setup the error logging to `oauth.log`, and consistently get the following error:

```
[2020-07-23 19:17:20] oauth-error-log.ERROR: OAuth IdentityProviderException: OAuthException: Can't Load URL: The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and subdomains of your app to the App Domains field in your app settings. [] []
```

I've confirmed multiple times that I have the correct callback URL in the `Valid OAuth Redirect URIs`, and have all of the domains set in Settings > Basic > App Domains.

I've paused on getting Facebook to work after a couple hours of troubleshooting. I was able to get Google authentication up and running in about 30 minutes, but did notice it was setting the redirect URL to `http` even though my site is running `https`.

Running Silverstripe 4.6.0, silverstripe-oauth-login 2.1.0

**Comment by kinglozzer** [comment]
I remember running into this... from memory, it was the Valid OAuth Redirect URIs option that was causing the issue (despite the misleading error message from Facebook!). I have a live site working with the following:

- OAuth redirect URIs: `https://www.mysite.com/oauth/callback` - note no trailing slash
- Settings > Basic:
    - App domains: `mysite.com` (no leading www, despite the live site running on www.!)
    - Site URL: `https://www.mysite.com/`
- Settings > Advanced:
    - Domain manager: `https://www.mysite.com/` - Exact match (though I don’t think domain manager would be related to this issue)

**Comment by jsirish** [comment]
@kinglozzer awesome thanks for the tips, I'll try it out this afternoon. Cheers!

**Comment by kinglozzer** [comment]
@jsirish I’m going to close this as it looks like an issue with Facebook more than the module, good luck!
