### ISSUE TITLE
Cannot log out when the OAuth Authenticator is the only Authenticator

### ISSUE THREAD

**Issue by MrJamesEllis** [bigfork/silverstripe-oauth-login#23]
Hi folks

When the `Bigfork\SilverStripeOAuth\Client\Authenticator\Authenticator` is the only authenticator, eg. when the Member or MFA authenticator is removed, members cannot log out of a site as  the OAuth Authenticator doesn't provide a logout service:

> https://github.com/bigfork/silverstripe-oauth-login/blob/master/src/Authenticator/Authenticator.php#L20

Adding a LogoutHandler to the authenticator would allow members signed in after the token handling process to sign out via a link or a form.
At the present these members get an error when hitting Security/logout

Diff:
```shell
$ diff Authenticator.php AuthenticatorWithLogout.php
8a9
> use SilverStripe\Security\MemberAuthenticator\LogoutHandler;
20c21
<         return SilverStripeAuthenticator::LOGIN;
---
>         return SilverStripeAuthenticator::LOGIN | SilverStripeAuthenticator::LOGOUT;
40c41
<         // No-op
---
>         return LogoutHandler::create($link, $this);
```

Maybe a subclass or specific LogoutHandler is needed instead of using the SilverStripe\Security\MemberAuthenticator\LogoutHandler ?

Cheers
J

**Comment by kinglozzer** [comment]
Good catch! I don’t see any reason why we can’t use `SilverStripe\Security\MemberAuthenticator\LogoutHandler` for this. We could subclass it (or register an injector service) so it can be overridden, but I don’t think devs will need to do that often so it’s probably overkill

**Comment by kinglozzer** [comment]
Closed in https://github.com/bigfork/silverstripe-oauth-login/pull/24, tagged in `2.2.0`
