### ISSUE TITLE
LoginFormTest_Controller AbsoluteLink method needs updating

### ISSUE THREAD

**Issue by MrJamesEllis** [bigfork/silverstripe-oauth-login#28]
Hi

See https://github.com/silverstripe/silverstripe-framework/commit/73ef035bd8ddfb6f386b78d4d9c957b4859d9a99 for when this was introduced, it is causing the following error:

```
Declaration of Bigfork\SilverStripeOAuth\Client\Test\Form\LoginFormTest_Controller::AbsoluteLink() must be compatible with SilverStripe\Control\RequestHandler::AbsoluteLink($action = '')
```

Pretty simple fix or need a PR?

Thanks
James

**Comment by lozcalver** [comment]
Fixed in `2.3.1`, thanks
