### ISSUE TITLE
How to handle Facebook users that don't send the email address?

### ISSUE THREAD

**Issue by wernerkrauss** [bigfork/silverstripe-oauth-login#3]
Somehow my Email address is not public on facebook and therefor everytime i login i create a new user in the database.

**Comment by wernerkrauss** [comment]
oh, i cannot access email, cause the demoapp during dev isn't live yet

**Comment by kinglozzer** [comment]
Just commenting this before Slack (and my memory) archive this and it’s lost:

Apparently this behaviour is unique to Facebook (https://github.com/thephpleague/oauth2-facebook/issues/7). I’m not sure how best to handle it, though Facebook has a few suggestions: https://developers.facebook.com/docs/facebook-login/handling-declined-permissions. Short-term, showing an error message and making users re-authenticate until they provide an email is probably the easiest fix.

It might also be worth properly investigating if it’s possible to get this module to work _without_ relying on emails. I imagine that would need to be optional (i.e. a config to enable/disable requiring email), which might be quite tricky.

**Comment by kinglozzer** [comment]
I’ve been rubberducking the “let’s not use emails at all” idea, my proposal for that is in https://github.com/bigfork/silverstripe-oauth-login/issues/7

**Comment by kinglozzer** [comment]
This has been resolved by https://github.com/bigfork/silverstripe-oauth-login/commit/b90209fcbbef5c4c6dfeb6aa74dba2dadc768f4a
